### ISSUE TITLE
port unittests to python3

### ISSUE THREAD

**Issue by sandrotosi** [nicolasff/webdis#173]
Hello,
as part of the Python2 removal effort in debian, i've just ported the unittests to python3, here attached the patch i used; please feel free to include it in this repo.

Regards,
Sandro

[webdis-python3.patch.txt](https://github.com/nicolasff/webdis/files/4460215/webdis-python3.patch.txt)

**Comment by nicolasff** [comment]
Hi Sandro,

Thanks for the patch, that's great! Do you want to re-open this issue as a pull request so that you appear as the author of this change in git logs, and get credit for this work?
The CI job will likely fail since the validation step uses Python 2.7, but I can address that once the changes are merged.

**Comment by sandrotosi** [comment]
naah i really dont care about credit, just apply and merge it :)

**Comment by nicolasff** [comment]
I've integrated your patch. Thanks again!
