### ISSUE TITLE
REDIS 6 now offers TLS, will Webdis?

### ISSUE THREAD

**Issue by cilex-ft** [nicolasff/webdis#201]
We manage hundreds of servers, each with their own redis / webdis server. 

Webdis now supports user/password to connect to Redis, so we can consider moving to 1 single Redis server or cluster while ensuring good data isolation between our servers and clients.

However the data flow on the internal network between webdis / redis might be read by an attacker.

We have measures to secure our internal network, such as: we encrypt all the internal traffic (to mysql, between reverse proxies and web servers behind...); all servers run a firewall to avoid attacks from peers; webdis servers only answer on 127.0.0.1; and undisclosed more.

I couldn't find an include to hiredis_ssl.h in webdis code, so it's my understanding that you don't yet support [hiredis ssl/tls](https://github.com/redis/hiredis/tree/v1.0.0#ssltls-support) - am I right?

It would be great if you can consider adding this feature.

**Comment by nicolasff** [comment]
Hi @cilex-ft,

That's correct, webdis doesn't support TLS connections to redis. I see that TLS was only added in Redis 6, so this is relatively new feature that webdis doesn't support.

I completely get how important it is, and it seems like a good idea to add it. I can't really make such changes myself due to IP restrictions linked to my current job, but have been helping a contributor recently who's made a lot of important fixes to webdis so I'll talk to him about what this involves and whether he's interested in taking this on.

Let's keep this open as a reference issue and an eventual PR can link to it.

Thanks for the suggestion!

**Comment by cilex-ft** [comment]
Thanks for delivering this, and sorry for my delay answering, daily operations don't leave much time for experimenting. 
Our choices would be 
1) using a package, or 
2) build if required, then deliver to containers via ansible. 
We don't use Docker (and we won't). 
We should find some time in november to test... sounds great!

**Comment by nicolasff** [comment]
I don't manage the packages for distros, this would be too much work that is better left to folks who are much more familiar with their specific platforms than I could ever be. Some even take care of it very quickly, e.g. 0.1.18 was tagged on [October 22](https://github.com/nicolasff/webdis/releases/tag/0.1.18) and updated in Homebrew just [3 days later](https://github.com/Homebrew/homebrew-core/commit/0062b18bf90d76097a9131b4244cde41f268a3cb).

Either way, thanks @cilex-ft for suggesting this feature and thanks to @jessie-murray for the concise implementation (although a lot of it is from Hiredis).

Please do let me know if you encounter any issues; it feels like this is pretty solid from what I've tested but since this is the first time this feature is added it's always possible that something was missed.

**Comment by cilex-ft** [comment]
I'm happy to finally report that SSL works for us. 

Here is our server configuration:

```
#port 6379
port 0
tls-port 6379
# test certificates
tls-cert-file /etc/redis/tests/tls/redis.crt
tls-key-file /etc/redis/tests/tls/redis.key
tls-ca-cert-file /etc/redis/tests/tls/ca.crt
tls-dh-params-file /etc/redis/tests/tls/redis.dh
# clients don't need a certificate - https://redis.io/topics/encryption 
tls-auth-clients no
```

We don't need nor want to deal with client certificates, hence `tls-auth-clients no` (so only the server uses tls - like a webserver, client certificates are rarely used).

And on webdis (complete with daemon and redis authentication - v 0.1.20-dev compiled with SSL=1)

```
{
    "redis_host": "172.16.17.18",
    "redis_port": 6379,
    "redis_auth": ["arefg5p4_e0011","SOMEUGLYPASSWORDHERE"],

    "ssl": {
        "enabled": true,
        "ca_cert_bundle": "/etc/webdis/ca.crt"
    },

    "http_host": "0.0.0.0",
    "http_port": 7379,
    "threads": 2,

    "daemonize": true,
    "websockets": true,
    "pidfile": "/run/webdis/webdis.pid",

    "database": 0,

    "acl": [
        {
            "disabled":["*"]
        },
        {
            "ip": "127.0.0.1",
            "enabled": ["SET","GET","DEBUG","UPDATE","SUBSCRIBE","PUBLISH"]
        }
    ]
}
```

where `/etc/webdis/ca.crt` was copied from redis-server.

Thank you again for implementing this nice features.
