### ISSUE TITLE
ACL over websocket 

### ISSUE THREAD

**Issue by pagesailor** [nicolasff/webdis#240]
@nicolasff  Hi! It looks like ACL is not working for me over websocket. Is it not implemented, or can it be a configuration problem?

**Comment by nicolasff** [comment]
Hi  @pagesailor, thanks for this bug report.

I will look into it shortly and report what I find here.

**Comment by pagesailor** [comment]
@nicolasff Hi, sorry for harassing you about this, I know it's free software, and provided as is, but I really have to know if it's a problem with webdis, or is something wrong with our configuration. If you don't have the time to get into this, please let me know if it's a feature which should work (and if there will be a fix sometime), or if ACL was never implemented for websocket, and it won't work in the near future. If it's a bug, and will be fixed, we can work around it for now, but if not, we have to choose another solution. Thank you for your time and work!

**Comment by nicolasff** [comment]
Hey @pagesailor sorry about the delay. As you can see mentioned on this page there's a commit implementing it already, I'm reviewing it and expect to merge it today.

**Comment by pagesailor** [comment]
@nicolasff @jessie-murray thank you, you are both awesone! I didn't expect such a fast response. Wish you all the best!

**Comment by nicolasff** [comment]
@pagesailor you're welcome! And thanks @jessie-murray once again for WebSocket improvements.

Note that there is a limitation with ACLs and WebSocket clients, since the WS implementation doesn't support HTTP basic auth (is that even a thing?). This is documented in the [ACL section of the README](https://github.com/nicolasff/webdis#acls-and-websocket-clients), the main point being:

> These rules apply to WebSocket connections as well, although without support for HTTP Basic Auth filtering. IP filtering is supported.

If you want to see an example of what the response looks like for rejected commands, run Webdis locally and open `tests/websocket.html`. There you can create two clients, one JSON-based and one "raw" using the "RESP" Redis protocol – less commonly used I'm sure.
Once you've connected you can click on `DEBUG OBJECT foo` and if you're running with the default `webdis.json` or `webdis-prod.json` you'll see the error message and its format:

<img width="1389" alt="image" src="https://github.com/nicolasff/webdis/assets/7276/800ee6ad-7c8f-4bf3-a06f-4170f7d32ceb">

As noted in the README:

> The `http_status` code is an indicator of how Webdis would have responded if the client had used HTTP instead of a WebSocket connection, since WebSocket messages do not inherently have a status code.
